---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-helm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-helm.name" . }}
    helm.sh/chart: {{ include "redis-helm.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  build-cluster.sh: |
    #!/bin/bash
    set -ex

    MASTER_COUNT={{ .Values.clusterFactor | quote }}
    REPLICA_COUNT={{ .Values.replicationFactor | quote }}
    STS_NAME="{{ include "redis-helm.fullname" . }}"
    HEADLESS_SVC="{{ include "redis-helm.fullname" . }}-headless"
    NAMESPACE={{ .Release.Namespace | quote }}
    CLUSTER_DOMAIN={{ .Values.clusterDomain | quote }}

    # create cluster
    MASTER_0_IP="$(dig ${STS_NAME}-0-0.${HEADLESS_SVC}.${NAMESPACE}.svc.${CLUSTER_DOMAIN} +answer +short)"
    MASTERIPS=("${MASTER_0_IP}:6379");
    for (( masterNumber=1; masterNumber<=$((${MASTER_COUNT} - 1)); masterNumber++ ))
    do
      MASTERIP="$(dig ${STS_NAME}-${masterNumber}-0.${HEADLESS_SVC}.${NAMESPACE}.svc.${CLUSTER_DOMAIN} +answer +short)"
      MASTERIPS+=("${MASTERIP}:6379")
      echo "${MASTERIPS[@]}"
    done

    redis-cli -h ${MASTER_0_IP} -p 6379 \
      --cluster create ${MASTERIPS[@]} \
      --cluster-replicas 0 --cluster-yes

    for (( masterNumber=0; masterNumber<=$((${MASTER_COUNT} - 1)); masterNumber++ ))
    do
      MASTERID="$(redis-cli -h ${MASTER_0_IP} -p 6379 cluster nodes | grep ${MASTERIPS[${masterNumber}]} | cut -d" " -f1)"
      for (( replicaNumber=1; replicaNumber<=$REPLICA_COUNT; replicaNumber++ ))
      do
        REPLICAIP=$(dig ${STS_NAME}-${masterNumber}-${replicaNumber}.${HEADLESS_SVC}.${NAMESPACE}.svc.${CLUSTER_DOMAIN} +answer +short)

        redis-cli -h "${MASTER_0_IP}" -p 6379 \
          --cluster add-node "${REPLICAIP}:6379" \
          "${MASTER_0_IP}:6379" --cluster-slave --cluster-master-id "${MASTERID}"
      done
    done
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
---