---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "redis-cluster.name" . }}-headless
    helm.sh/chart: {{ include "redis-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.redisPort }}
      targetPort: redis
      protocol: TCP
      name: redis
    - port: {{ .Values.service.gossipPort }}
      targetPort: gossip
      protocol: TCP
      name: gossip
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "redis-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
